<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://www.Dummy.com"  xmlns:n="http://www.Dummy.com/Name/Types"  xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" targetNamespace="http://www.Dummy.com">
    <wsdl:types>
        <xs:schema>
            <xs:import namespace="http://www.Dummy.com/Common_namespace/Types" schemaLocation="./common_namespace.xsd"/>
            <xs:import namespace="http://www.Dummy.com/certificate_namespace/Types" schemaLocation="./certificate_namespace.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="DummyRequest">
        <wsdl:part xmlns:ns1="http://www.Dummy.com/certificate_namespace/Types" name="DummyRequest" element="ns1:DummyRequest"/>
    </wsdl:message>
    <wsdl:message name="DummyResponse">
        <wsdl:part xmlns:ns2="http://www.Dummy.com/certificate_namespace/Types" name="DummyResponse" element="ns2:DummyResponse"/>
    </wsdl:message>
    <wsdl:portType name="DummyPortType">
        <wsdl:operation name="FetchDummy">
            <wsdl:input message="ns1:DummyRequest"/>
            <wsdl:output message="ns2:DummyResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DummyBinding" type="tns:DummyPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="FetchDummy">
            <soap:operation soapAction="http://www.Dummy.com#FetchDummy" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>

        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DummyService">
        <wsdl:port name="DummyPortType" binding="tns:DummyBinding">
            <soap:address location="http://www.Dummy.com/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>

